# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/arter97/lawnchair/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/arter97/lawnchair

PRODUCT_COPY_FILES += \
    vendor/arter97/lawnchair/proprietary/system_ext/etc/permissions/privapp-permissions-app.lawnchair.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-app.lawnchair.xml \
    vendor/arter97/lawnchair/proprietary/system_ext/etc/sysconfig/app.lawnchair-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/app.lawnchair-hiddenapi-package-whitelist.xml \
    vendor/arter97/lawnchair/proprietary/system_ext/priv-app/Lawnchair/lib/arm64/libnrb.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/Lawnchair/lib/arm64/libnrb.so

PRODUCT_PACKAGES += \
    Lawnchair
